### ISSUE TITLE
I Can't start rpc_service.js as daemon - stuck on ask password.

### ISSUE THREAD

**Issue by minzak** [byteball/headless-byteball#19]
When i start **node rpc_service.js** - it is ask password, and i can insert it.
But how to start like a service/daemon?

For example **pm2 start /mnt/headless-byteball/play/rpc_service.js** - not worked, because it stuck on asked password.
How to set password in config or else place?
Thanks.

**Comment by pmiklos** [comment]
it's not secure by any means, but you can do this:

```
echo password | node rpc_service.js
```

**Comment by minzak** [comment]
Yes, it work in manual only mode, but this way not for daemons. It is not work for PM2.

My worked way is:
```
pm2 start ....
sleep 5
pm2 send 1 pass
```
