### ISSUE TITLE
Not able to find memory index reference in headers_commision.js

### ISSUE THREAD

**Issue by dhamadkd** [byteball/headless-byteball#22]
I did node start.js and things work ok with last line being as below
From this point, output will be redirected to C:\Users\dhama\AppData\Local/headless-byteball/log.txt
To release the terminal, type Ctrl-Z, then 'bg'

But suddenly it breaks with following issue:

D:\testbb\headless-byteball\node_modules\byteballcore\headers_commission.js:92
                                                                var next_mc_unit_props = storage.assocStableUnitsByMci[parent.main_chain_index+1].find(function(props){return props.is_on_main_chain});
                                                                                                                                                  ^

TypeError: Cannot read property 'find' of undefined
    at D:\testbb\headless-byteball\node_modules\byteballcore\headers_commission.js:92:91
    at Array.forEach (<anonymous>)
    at D:\testbb\headless-byteball\node_modules\byteballcore\headers_commission.js:90:22
    at Statement.<anonymous> (D:\testbb\headless-byteball\node_modules\byteballcore\sqlite_pool.js:115:6)

**Comment by tonyofbyteball** [comment]
It was fixed in more recent versions, please update the core.  Reopen if the issue persists.
