### ISSUE TITLE
Missing payments

### ISSUE THREAD

**Issue by smartpunter** [byteball/headless-byteball#3]
I installed and configured headless-byteball on Ubuntu using mysql database.
I managed to connect to it from my desktop wallet.
After issuing command 'address', it gives me byteball addresses, different each time.
I tried to send 1000 bytes to two such addresses, but for some reason they did not appear on balance. Both transactions have been 
That is unforgivable bug, so we need to figure out what's happened and try to fix it.
![image](https://cloud.githubusercontent.com/assets/10908605/26577099/84044768-452b-11e7-9ec5-3ba5de937335.png)

**Comment by tonyofbyteball** [comment]
Is your node synced?  I think I saw a similar issue from you some time ago.

**Comment by delorule** [comment]
same error

**Comment by ghost** [comment]
same error here.

**Comment by polyakoff** [comment]
Check if your node is synced as @tonyofbyteball suggested, it takes a while.
Use ```curl --data '{"jsonrpc":"2.0", "id":1, "method":"getinfo", "params":{} }' http://127.0.0.1:6332```
and waint until `counter unhandled` param will be close to zero.
[Source](https://github.com/byteball/headless-byteball/wiki/Running-RPC-service).
After sync finished, you should see your balance.
