### ISSUE TITLE
"Mandatory upgrade required: [..]" error, persists after clean install of headless-obyte

### ISSUE THREAD

**Issue by harryofskyrim** [byteball/headless-byteball#52]
I launched my headless wallet, and it ended up in an error that wasn't there before.
I tried to fix this by upgrading my nodejs to v10.16.3 and rebuilding the headless wallet from scratch, but the error persists.
A headless wallet that had been installed on a different machine a while ago, works just fine.

My actions:
```
git clone https://github.com/byteball/headless-obyte.git
cd headless-obyte
npm install
node start.js
```

After requesting the passphrase, it throws the following error:

```
/home/tl/Work/headless-obyte/node_modules/ocore/network.js:2404
                        throw Error("Mandatory upgrade required, please check the release notes at https://github.com/byteball/obyte-gui-wallet/releases and upgrade.");
                        ^

Error: Mandatory upgrade required, please check the release notes at https://github.com/byteball/obyte-gui-wallet/releases and upgrade.
    at handleJustsaying (/home/tl/Work/headless-obyte/node_modules/ocore/network.js:2404:10)
    at WebSocket.onWebsocketMessage (/home/tl/Work/headless-obyte/node_modules/ocore/network.js:3019:11)
    at WebSocket.emit (events.js:198:13)
    at Receiver.ontext (/home/tl/Work/headless-obyte/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/tl/Work/headless-obyte/node_modules/ws/lib/Receiver.js:536:18
    at /home/tl/Work/headless-obyte/node_modules/ws/lib/Receiver.js:368:7
    at /home/tl/Work/headless-obyte/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
```

Error links to a gui wallet github, it's hardcoded in ocore module.
Linking to an earlier commit of ocore in package.json, taken from the working headless wallet, results in the same error.

**Comment by tarmo888** [comment]
if you have set `testnet=1` in .env file then at the moment, you would need to use AA branch, otherwise you get this upgrade error.

**Comment by harryofskyrim** [comment]
I sure did have `testnet=1` set, thanks

> if you have set `testnet=1` in .env file then at the moment, you would need to use AA branch, otherwise you get this upgrade error.
